### ISSUE TITLE
Readme and requirements clarification

### ISSUE THREAD

**Issue by buzden** [Russoul/idris2-lua#1]
Hey, you've done a great job! I think at least two things should be added to the readme.

What is required/expected lua version? I've checked that your codegen does not work with 5.1 (accidentially installed on my machine).

Also, I think that it should be in the readme that not only Idris 2 should be installed but that Idris2 API library (i.e. those named `idris2`) should be installed also (e.g. using `make install-api` of Idris 2).

**Comment by Russoul** [comment]
Clarified this in the readme 39a71cd30ebcb0dced4a423382a61fd62237ddc9

**Comment by buzden** [comment]
Great, thanks!
