### ISSUE TITLE
Error: Module Libraries.Data.Bool.Extra not found

### ISSUE THREAD

**Issue by I-B-3** [Russoul/Idris2-Lua#5]
Trying to install with Idris 2, v0.3.0, and I get this:

```
$ make all && make install
idris2 --build idris2-lua.ipkg
1/4: Building LuaCommon (src\LuaCommon.idr)
2/4: Building OrderDefs (src\OrderDefs.idr)
3/4: Building LuaAst (src\LuaAst.idr)
Error: Module Libraries.Data.Bool.Extra not
found

LuaGen:9:1--9:33
 5 |
 6 | import Core.Context
 7 | import Core.Directory
 8 |
 9 | import Libraries.Data.Bool.Extra
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

make: *** [Makefile:36: build/exec/idris2-lua] Error 1
```

Is Idris2-Lua compatible with v0.3.0?

**Comment by Russoul** [comment]
Are you using the release build? Probably won’t work, too much has changed internally in Idris 2 since 0.3.0. Please use the version (commit) of Idris 2 mentioned in the README of Idris2-Lua. You can try building against the latest master too, but I can’t guarantee it will work.

**Comment by I-B-3** [comment]
I was building against the latest master. Have just tried it with [0.3.0-349308396](https://github.com/idris-lang/Idris2/tree/349308396c1ad2579eb75084c2ab51ec2ee5e110) but ran into different errors, I don't know if it's worth creating issues for them though as they're because I'm on Windows and I don't know if you expect that to work. I'll close this issue as with the supported version of Idris 2 this wasn't an issue.

**Comment by Russoul** [comment]
Yeah, I haven't tested it on Windows at all. And don't really plan to.
